# Generated by Django 5.2.8 on 2025-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinkhole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('diameter', models.FloatField(help_text='Diameter in meters')),
                ('depth', models.FloatField(help_text='Depth in meters')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=10)),
                ('geological_type', models.CharField(choices=[('KARST', 'Karst'), ('DISSOLUTION', 'Dissolution'), ('SUBSIDENCE', 'Subsidence'), ('COLLAPSE', 'Collapse'), ('ANTHROPOGENIC', 'Anthropogenic')], max_length=20)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('bedrock_type', models.CharField(blank=True, max_length=100)),
                ('water_table_depth', models.FloatField(blank=True, help_text='Water table depth in meters', null=True)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('last_inspection', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the sinkhole currently active/expanding?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
